name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Write access to push to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install markdown jinja2

      - name: Generate Site
        run: |
          source venv/bin/activate
          python gen.py docs  # Keep generating the site in the `docs/` folder

      - name: Add .nojekyll to avoid Jekyll processing
        run: |
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the `gh-pages` branch
          folder: docs   # Deploy the entire `docs` folder, which contains your generated files
          clean: true    # Clean the folder before deployment
          commit-message: "Deploy generated site to GitHub Pages"

